### ISSUE TITLE
Methods not recognized in TypeScript

### ISSUE THREAD

**Issue by stefalda** [alexziskind1/nativescript-effects#3]
Hi Alex,
 thanks for this useful library.

I've got some problems using it in a typescript project because even if the d.ts file is present, the compiler is complaining about missing methods in the View:

`error TS2339: Property 'fadeOut' does not exist on type 'Image'.`

It works but it's not as smooth as I'd like.

Do you know how to fix this?

Thanks

Stefano

**Comment by alexziskind1** [comment]
Re: typescript defs: Add to references.d.ts /// <reference
path="../node_modules/nativescript-effects/tns-effects.d.ts" />

Thanks Stefano

Sendt fra min iPhone

On Feb 27, 2016, at 10:34 AM, Stefano Falda notifications@github.com
wrote:

Hi Alex,
thanks for this useful library.

I've got some problems using it in a typescript project because even if the
d.ts file is present, the compiler is complaining about missing methods in
the View:

error TS2339: Property 'fadeOut' does not exist on type 'Image'.

It works but it's not as smooth as I'd like.

Do you know how to fix this?

Thanks

Stefano

—
Reply to this email directly or view it on GitHub
https://github.com/alexziskind1/nativescript-effects/issues/3.

**Comment by stefalda** [comment]
Great Alex!
It works like a charm!
Thank you

**Comment by toddanglin** [comment]
I think this would be an useful tip to add to the README! :)

**Comment by alexziskind1** [comment]
@toddanglin yes, this is a good temporary fix! I want to revisit this and add TypeScript support soon.

**Comment by toddanglin** [comment]
Created a quick PR for the README in the meantime 👍
